project_name: Default
working_dir: "."
cmd:
- python main.py
provisioning:
  gpu_type: h100
  gpu_count: 1
  cpu_count: 20
  ram: 160
  blank: false
teamcity:
  url: https://api.cadence.jetbrains.com
  build_conf_id: id34a96c5642ff42e99cf48f3b18cd4564_JetTrain
env:
  variables: {}
  python:
    pip:
      requirements_path: requirements.txt
    version: "3.10"
  secrets:
    variables: {}
    ssh_keys: []
  aws:
    sync_config: false
    sync_credentials: false
    sync_cache: false
project_sync:
  local:
    root: "."
    storage_name: Cadence Storage
    uri: ""
    exclude:
    - E:/Pycharm/FoodDetect
    - Viet67/.venv/**
    include: []
    sync_back: false
    snapshots: true
    storage_type: DEFAULT
inputs: []
outputs:
- type: OUTPUT
  storage_name: Cadence Storage
  uri: ""
  path: "."
  acceleration: false
  storage_type: DEFAULT
mounts: []
storages: []
description: ""
